apiVersion: v1
kind: ConfigMap
metadata:
  name: user-dev-hdfs-cluster1
  namespace: user
data:
  hdfs-site.xml: |-
    <configuration>

      <property>
        <name>dfs.nameservices</name>
        <value>hdfs-user-dev-01</value>
      </property>

      <property>
        <name>dfs.ha.namenodes.hdfs-user-dev-01</name>
        <value>nn1,nn2</value>
      </property>

      <property>
        <name>dfs.namenode.rpc-address.hdfs-user-dev-01.nn1</name>
        <value>hadoop-0.hdfs-user-dev-01.user.svc.cluster.local:8020</value>
      </property>

      <property>
        <name>dfs.namenode.rpc-address.hdfs-user-dev-01.nn2</name>
        <value>hadoop-1.hdfs-user-dev-01.user.svc.cluster.local:8020</value>
      </property>

      <property>
        <name>dfs.namenode.http-address.hdfs-user-dev-01.nn1</name>
        <value>hadoop-0.hdfs-user-dev-01.user.svc.cluster.local:50070</value>
      </property>

      <property>
        <name>dfs.namenode.http-address.hdfs-user-dev-01.nn2</name>
        <value>hadoop-1.hdfs-user-dev-01.user.svc.cluster.local:50070</value>
      </property>

      <property>
        <name>dfs.namenode.shared.edits.dir</name>
        <value>qjournal://hadoop-0.hdfs-user-dev-01.user.svc.cluster.local:8485;hadoop-1.hdfs-user-dev-01.user.svc.cluster.local:8485;hadoop-2.hdfs-user-dev-01.user.svc.cluster.local:8485/hdfs-user-dev-01</value>
      </property>

      <property>
        <name>dfs.client.failover.proxy.provider.hdfs-user-dev-01</name>
        <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
      </property>

      <property>
        <name>dfs.ha.fencing.methods</name>
        <value>sshfence</value>
      </property>

      <property>
        <name>dfs.ha.fencing.ssh.private-key-files</name>
        <value>/root/.ssh/id_rsa</value>
      </property>

      <property>
        <name>dfs.replication</name>
        <value>3</value>
      </property>

      <property>
        <name>dfs.permissions.enabled</name>
        <value>false</value>
      </property>

      <property>
        <name>dfs.ha.automatic-failover.enabled</name>
        <value>true</value>
      </property>

      <property>
        <name>ha.zookeeper.quorum</name>
        <value>zk-0.zk-user-dev-01.user.svc.cluster.local:2181,zk-1.zk-user-dev-01.user.svc.cluster.local:2181,zk-2.zk-user-dev-01.user.svc.cluster.local:2181</value>
      </property>

      <property>
        <name>dfs.journalnode.edits.dir</name>
        <value>/data/jn/edits</value>
      </property>

      <property>
        <name>dfs.namenode.name.dir</name>
        <value>/data/nn/name</value>
      </property>

      <property>
        <name>dfs.datanode.data.dir</name>
        <value>/data/dn/data</value>
      </property>

      <property>
        <name>dfs.namenode.checkpoint.dir</name>
        <value>/data/nn/checkpoint</value>
      </property>

    </configuration>


  core-site.xml: |-
    <configuration>

      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://hdfs-user-dev-01</value>
      </property>

      <property>
        <name>hadoop.tmp.dir</name>
        <value>/data/hadoop/tmp</value>
      </property>

    </configuration>


  mapred-site.xml: |-
    <configuration>
      <property>
        <name>mapreduce.framework.name</name>
        <value>yarn</value>
      </property>
      <property>
        <name>mapreduce.jobhistory.address</name>
        <value>192.168.114.111:10020</value>
      </property>
      <property>
        <name>mapreduce.jobhistory.webapp.address</name>
        <value>192.168.114.111:19888</value>
      </property>
      <property>
        <name>mapreduce.job.ubertask.enable</name>
        <value>true</value>
      </property>
    </configuration>
