---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hdfs-pdb
  namespace: user
spec:
  selector:
    matchLabels:
      app: hdfs
  maxUnavailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop
  namespace: user
spec:
  selector:
    matchLabels:
      app: hadoop
  serviceName: hdfs-user-dev-01
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      nodeSelector:
        shileizcc.com/schedule-hbase-01: "true"
      tolerations:
      - key: "special"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "organization"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"
      - key: "application"
        operator: "Equal"
        value: "bigdata"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - hadoop
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hdfs
        imagePullPolicy: Always
        image: slzcc/hadoop:3.2.1-supervisord
        resources:
          requests:
            memory: "10000Mi"
            cpu: "20"
        ports:
        - containerPort: 8485
          name: p8485
        - containerPort: 8020
          name: p8020
        - containerPort: 8480
          name: p8480
        - containerPort: 50070
          name: p50070
        - containerPort: 50020
          name: p50020
        - containerPort: 50075
          name: p50075
        volumeMounts:
        - name: datadir
          mountPath: /data
        - name: hdfs-config
          mountPath: /opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml
        - name: hdfs-config
          mountPath: /opt/hadoop-3.2.1/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - mountPath: /usr/share/zoneinfo
          name: usr-local-timezone
          readOnly: true
        command:
        - /start-supervisord
        securityContext:
          runAsUser: 0
        env:
        - name: HADOOP_NAMENODE_DIR
          value: '/data/nn'
        - name: isCUSTOM
          value: 'false'
        - name: TZ
          value: Asia/Shanghai
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "/check-ready 8480"
          initialDelaySeconds: 60
          timeoutSeconds: 60
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo
          type: DirectoryOrCreate
        name: usr-local-timezone
      - name: datadir
        hostPath:
          path: '/data/server/kubernetes/hadoop'
      - name: hdfs-config
        configMap:
          name: user-dev-hdfs-cluster1
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hdfs-site.xml
            path: hdfs-site.xml
          - key: mapred-site.xml
            path: mapred-site.xml
